### ISSUE TITLE
Cotizaciones

### ISSUE THREAD

**Issue by fahenao** [fahenao/_cultural_portobelo#84]
## Problem
Como empresa, quiero cotizarle al gobierno desde mi página, porque tengo toda la información de los libros lo que evita llenar estos campos manualmente.

## Current behavior
Como empresa, debo crear un documento de word con toda la información relacionada a los libros, cada ves que le voy a cotizar al gobierno.

## Expected behavior
Como empresa, deseo poder crear y administrar mis cotizaciones en general desde la página.

## Acceptance criteria

-  Encabezado:
  -  [ ]  La cotización debe tener los siguientes detalles:
    -  [ ]  Encabezado de la empresa
    -  [ ]  Logo de la empresa
    -  [ ]  Fecha
    -  [ ]  Nombre de cliente
    -  [ ]  Atención
    -  [ ]  Número de cotización (número único)
    -  [ ]  Condición [(50% de anticipo, 50% contra entrega), (crédito), (contado)]
###  Acciones: crear, editar, update, destroy(only admin)
-  Cuerpo de la cotización
  -  [ ]  Debo poder asignarle un cliente
  -  [ ]  Debo poder agregar uno o varios libros.
